export function appTemplate(mac: boolean) {
  return `
  <aside class="sidebar" aria-label="文档导航">
    <div class="sidebar-top"><span class="brand"><i data-lucide="leaf"></i>叶笺</span><button class="icon-button" id="hide-sidebar" title="收起侧栏" aria-label="收起侧栏"><i data-lucide="panel-left"></i></button></div>
    <div class="sidebar-switch"><button id="documents-tab" aria-selected="false">文档</button><button id="outline-tab" class="selected" aria-selected="true">大纲</button></div>
    <div class="nav-content"><p class="section-label" id="nav-label">当前文档</p><nav id="outline" aria-label="文档大纲"></nav><section id="documents" hidden><input id="folder-filter" placeholder="筛选 Markdown…" aria-label="筛选 Markdown 文件"><div class="folder-tools"><button id="open-folder">打开文件夹…</button><button id="folder-new" title="新建工作区文件">＋</button><button id="folder-refresh" title="刷新">↻</button></div><div id="folder-tree"></div><p class="section-label">近期文档</p><div id="recent-files"></div></section></div>
  </aside>
  <main class="workspace">
    <header class="titlebar"><button class="icon-button" id="show-sidebar" title="展开侧栏" aria-label="展开侧栏" hidden><i data-lucide="panel-left"></i></button><div class="document-tab"><i data-lucide="file-text"></i><span id="document-name">A small thought.md</span><span id="dirty-dot" hidden aria-label="未保存">●</span></div><button class="icon-button" id="new-file" title="新建文档" aria-label="新建文档"><i data-lucide="plus"></i></button><div class="titlebar-space"></div><button class="icon-button" id="more-actions" title="更多操作" aria-label="更多操作">⋯</button><button class="icon-button" id="save-file" title="保存文档" aria-label="保存文档"><i data-lucide="save"></i></button><button class="icon-button" id="theme-toggle" title="切换主题" aria-label="切换主题"><i data-lucide="moon"></i></button></header>
    <div class="app-actions" hidden><button id="file-menu-toggle">文件</button><button id="format-menu-toggle">格式</button><button id="find-toggle">查找</button><button id="reading-toggle">阅读</button><button id="settings-toggle">设置</button></div><div id="tab-list" class="tab-list" aria-label="打开的文档"></div><section id="editor" aria-label="Markdown 书写区"></section><article id="reading-view" class="markdown-body" hidden></article><section id="welcome-view" hidden><h1>给想法一点空间。</h1><p>从一页空白开始，或打开本地 Markdown 文件。</p><button id="welcome-new" class="primary">新建文档</button><button id="welcome-open">打开文件…</button></section>
    <footer class="statusbar"><div><span id="word-count">0 字</span><span id="read-time">1 分钟阅读</span></div><div><span id="save-status" role="status">就绪</span><span>UTF-8</span><span id="edit-mode">原位编辑</span><button id="mode-toggle" title="切换原位编辑与源码">源码</button></div></footer>
  </main>
  <div id="format-toolbar" class="format-toolbar" role="toolbar" aria-label="格式工具栏" hidden>
    <button data-format="bold" title="加粗" aria-label="加粗"><i data-lucide="bold"></i></button><button data-format="italic" title="斜体" aria-label="斜体"><i data-lucide="italic"></i></button><button data-format="strike" title="删除线" aria-label="删除线"><i data-lucide="strikethrough"></i></button><button data-format="code" title="行内代码" aria-label="行内代码"><i data-lucide="code"></i></button><button data-format="h1" title="一级标题" aria-label="一级标题"><i data-lucide="heading-1"></i></button><button data-format="h2" title="二级标题" aria-label="二级标题"><i data-lucide="heading-2"></i></button><button data-format="h3" title="三级标题" aria-label="三级标题"><i data-lucide="heading-3"></i></button><button data-format="bullet" title="无序列表" aria-label="无序列表"><i data-lucide="list"></i></button><button data-format="ordered" title="有序列表" aria-label="有序列表"><i data-lucide="list-ordered"></i></button><button data-format="task" title="任务列表" aria-label="任务列表"><i data-lucide="list-checks"></i></button><button data-format="quote" title="引用" aria-label="引用"><i data-lucide="quote"></i></button><button data-format="link" title="链接" aria-label="链接"><i data-lucide="link"></i></button><button data-format="image" title="图片" aria-label="图片"><i data-lucide="image"></i></button><button data-format="table" title="表格" aria-label="表格"><i data-lucide="table"></i></button><button data-format="codeblock" title="代码块" aria-label="代码块"><i data-lucide="square-code"></i></button><button data-format="hr" title="分隔线" aria-label="分隔线"><i data-lucide="minus"></i></button>
  </div>
  <dialog id="unsaved-dialog"><h2>先保存这段想法？</h2><p>当前文档有未保存的修改。</p><div class="dialog-actions"><button value="cancel">取消</button><button value="discard">不保存</button><button value="save" class="primary">保存</button></div></dialog>
  <div class="toast" id="toast" role="alert" hidden></div>
`;
}
