// Code generated by `mygo generate`. DO NOT EDIT.

import { call } from "mygo-runtime";

// ---- Types ----

export interface Document {
  id: string;
  name: string;
  path: string;
  content: string;
  dirty: boolean;
}

export interface ExportedSession {
  id: string;
  name: string;
  path: string;
  content: string;
  dirty: boolean;
  savedContent: string;
}

export interface ExternalState {
  changed: boolean;
  missing: boolean;
}

export interface Folder {
  name: string;
  path: string;
}

export interface ImportResult {
  path: string;
  dataURI: string;
}

export interface Node {
  name: string;
  path: string;
  directory: boolean;
  children?: Node[];
}

export interface RecentDocument {
  name: string;
  path: string;
  openedAt: string;
}

export interface SessionState {
  currentId: string;
  documents: ExportedSession[];
}

export interface State {
  workspace: Folder | null;
  recent: RecentDocument[];
}

export interface WorkspaceDocument {
  name: string;
  path: string;
  relative: string;
  content: string;
}

// ---- Services ----

/** Files 仅提供用户通过原生文件选择框授权的文档操作。 */
export const Files = {
  checkExternal(id: string): Promise<ExternalState> {
    return call("Files.CheckExternal", id);
  },
  close(id: string): Promise<void> {
    return call("Files.Close", id);
  },
  current(): Promise<Document> {
    return call("Files.Current");
  },
  draft(id: string, content: string): Promise<void> {
    return call("Files.Draft", id, content);
  },
  exportMarkdown(id: string, content: string): Promise<string> {
    return call("Files.ExportMarkdown", id, content);
  },
  list(): Promise<Document[]> {
    return call("Files.List");
  },
  new(): Promise<Document> {
    return call("Files.New");
  },
  newNamed(name: string): Promise<Document> {
    return call("Files.NewNamed", name);
  },
  open(): Promise<Document | null> {
    return call("Files.Open");
  },
  openRecent(path: string): Promise<Document> {
    return call("Files.OpenRecent", path);
  },
  openWorkspace(relative: string): Promise<Document> {
    return call("Files.OpenWorkspace", relative);
  },
  reload(id: string, discardDirty: boolean): Promise<Document> {
    return call("Files.Reload", id, discardDirty);
  },
  save(id: string, content: string, saveAs: boolean): Promise<Document | null> {
    return call("Files.Save", id, content, saveAs);
  },
  select(id: string): Promise<Document> {
    return call("Files.Select", id);
  },
  session(): Promise<SessionState> {
    return call("Files.Session");
  },
} as const;

/** Workspace 可以直接通过 mygo.Bind(&Workspace{}) 绑定；零值和构造函数均延迟初始化。 */
export const Workspace = {
  browseImage(documentPath: string): Promise<string> {
    return call("Workspace.BrowseImage", documentPath);
  },
  clearRecent(): Promise<void> {
    return call("Workspace.ClearRecent");
  },
  copyText(text: string): Promise<void> {
    return call("Workspace.CopyText", text);
  },
  createFile(relative: string): Promise<void> {
    return call("Workspace.CreateFile", relative);
  },
  createFolder(relative: string): Promise<void> {
    return call("Workspace.CreateFolder", relative);
  },
  current(): Promise<State> {
    return call("Workspace.Current");
  },
  exportHTML(name: string, html: string): Promise<string> {
    return call("Workspace.ExportHTML", name, html);
  },
  openDocument(relative: string): Promise<WorkspaceDocument | null> {
    return call("Workspace.OpenDocument", relative);
  },
  openExternal(raw: string): Promise<void> {
    return call("Workspace.OpenExternal", raw);
  },
  openFolder(): Promise<Folder | null> {
    return call("Workspace.OpenFolder");
  },
  openRecent(path: string): Promise<WorkspaceDocument | null> {
    return call("Workspace.OpenRecent", path);
  },
  print(): Promise<void> {
    return call("Workspace.Print");
  },
  recent(): Promise<RecentDocument[]> {
    return call("Workspace.Recent");
  },
  /** Remember 只接受工作区相对路径，不用近期记录赋予任意绝对路径访问权限。 */
  remember(relative: string): Promise<void> {
    return call("Workspace.Remember", relative);
  },
  rename(oldRelative: string, newRelative: string): Promise<void> {
    return call("Workspace.Rename", oldRelative, newRelative);
  },
  showInFolder(path: string): Promise<void> {
    return call("Workspace.ShowInFolder", path);
  },
  tree(): Promise<Node[]> {
    return call("Workspace.Tree");
  },
} as const;

/** Assets 仅凭已打开文档 ID 取得后端授权路径，不接收前端提供的文档路径。 */
export const Assets = {
  importImage(id: string): Promise<ImportResult | null> {
    return call("Assets.ImportImage", id);
  },
  readImage(id: string, resource: string): Promise<string> {
    return call("Assets.ReadImage", id, resource);
  },
} as const;
